"""
Default units for nutrition fields.
"""

DEFAULT_UNITS = {
    "Takaran Saji": "g",
    "Sajian per Kemasan": "serving",
    "Energi Total": "kcal",
    "Energi dari Lemak Jenuh": "kcal",
    "Energi dari Lemak": "kcal",
    "Lemak Trans": "g",
    "Lemak Tidak Jenuh Tunggal": "g",
    "Lemak Tidak Jenuh Ganda": "g",
    "Lemak Jenuh": "g",
    "Lemak Total": "g",
    "Kolesterol": "mg",
    "Protein": "g",
    "Karbohidrat Total": "g",
    "Serat Pangan": "g",
    "Gula Total": "g",
    "Gula": "g",
    "Sukrosa": "g",
    "Natrium": "mg",
    "Vitamin D": "mcg",
    "Vitamin E": "mg",
    "Vitamin B1": "mg",
    "Vitamin B2": "mg",
    "Vitamin B3": "mg",
    "Vitamin B6": "mg",
    "Vitamin B12": "mcg",
    "Vitamin C": "mg",
    "Vitamin A": "mcg",
    "Kalium": "mg",
    "Kalsium": "mg",
    "Fosfor": "mg",
    "Magnesium": "mg",
    "Zat Besi": "mg",
    "Zink": "mg",
    "Selenium": "mcg",
}
